// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/lucasd-coder/business-service/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// AuthRepository_internal_domain_user is an autogenerated mock type for the AuthRepository type
type AuthRepository_internal_domain_user struct {
	mock.Mock
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *AuthRepository_internal_domain_user) FindByEmail(ctx context.Context, email string) (*model.GetUserResponse, error) {
	ret := _m.Called(ctx, email)

	var r0 *model.GetUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.GetUserResponse, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.GetUserResponse); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GetUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, pld
func (_m *AuthRepository_internal_domain_user) Register(ctx context.Context, pld *model.Register) (*model.RegisterUserResponse, error) {
	ret := _m.Called(ctx, pld)

	var r0 *model.RegisterUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Register) (*model.RegisterUserResponse, error)); ok {
		return rf(ctx, pld)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Register) *model.RegisterUserResponse); ok {
		r0 = rf(ctx, pld)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RegisterUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Register) error); ok {
		r1 = rf(ctx, pld)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthRepository_internal_domain_user interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthRepository_internal_domain_user creates a new instance of AuthRepository_internal_domain_user. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthRepository_internal_domain_user(t mockConstructorTestingTNewAuthRepository_internal_domain_user) *AuthRepository_internal_domain_user {
	mock := &AuthRepository_internal_domain_user{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
