version: '3.4'

services:
  accessauthservice:
    entrypoint: ./.docker/entrypoint.sh
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    volumes:
      - .:/go/src
    env_file:
      - .env
