version: '3.4'

services:
  business-service:
    container_name: business-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    volumes:
      - .:/go/src
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123"
      RABBITMQ_DEFAULT_VHOST: "fastfeet"    
    ports:
      - "15672:15672"
      - "5672:5672"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

