version: '3.4'

services:
  user-manger-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    volumes:
      - .:/go/src
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  mongodb:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_DATABASE: user-manger-service
      MONGODB_ROOT_USER: admin
      MONGODB_ROOT_PASSWORD: admin123  
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123  
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:      
      - ./infra/mongo:/docker-entrypoint-initdb.d/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

