# OIDC Configuration

application:
  realm: fastfeet

"%dev":
  quarkus:
    application:
      name: access-auth-service
    http:
      port: 8081
      root-path: access-auth-service
      access-log:
        pattern: "...traceId=%{X,traceId} spanId=%{X,spanId}"
    log:
      console:
        format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
        level: DEBUG
      level: INFO
      min-level: DEBUG
      category:
        "org.keycloak":
          level: ERROR
        "io.quarkus":
          level: INFO
    oidc:
      auth-server-url: http://localhost:8080/realms/fastfeet
      client-id: ${CLIENT_ID:access-auth-service}
      credentials:
        secret: ${CLIENT_SECRET:OO6s0DTZE1BN0HSLkZyk0I9utmbrgC9n}
      tls:
        verification: none
      token: 
        issuer: any     
  
  # Enable Policy Enforcement
    keycloak:
      admin-client:
        server-url: http://localhost:8080
        realm: fastfeet  
        client-id: ${ADMIN_ID:admin-cli}
        password: ${ADMIN_PASSWORD:admin}
        username: ${ADMIN_USERNAME:admin}
        client-secret: ${ADMIN_SECRET:a951803a-79c7-46a6-8197-e32835286971}     
        grant-type: PASSWORD
      devservices:
        enabled: false
      policy-enforcer:
        enable: true
        paths:
          1:
            path: /api/register
            enforcement-mode: DISABLED
    
    otel:
      exporter:
        otlp:
          traces:
            endpoint: http://localhost:14278
