app:
  name: user-manger-service
  version: 1.0.0

logger:
  log_level: ${LOG_LEVEL}

grpc:
  port: ${GRPC_PORT}

http:
  port: ${HTTP_PORT}
  timeout: 20s

mongodb:
  url: ${MONGODB_URL}
  connTimeout: 10s
  database: fast-feet
  collections:
    user:
      collection: "users"

integration:
  otlp:
      url: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      protocol: grpc
      timeout: 20s