// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/lucasd-coder/user-manger-service/config"
	"github.com/lucasd-coder/user-manger-service/internal/domain/user/repository"
	"github.com/lucasd-coder/user-manger-service/internal/domain/user/service"
	"github.com/lucasd-coder/user-manger-service/pkg/mongodb"
)

// Injectors from wire.go:

func InitializeUserRepository() *repository.UserRepository {
	configConfig := config.GetConfig()
	client := mongodb.GetClientMongoDB()
	userRepository := repository.NewUserRepository(configConfig, client)
	return userRepository
}

func InitializeUserService() *service.UserService {
	userRepository := InitializeUserRepository()
	userService := service.NewUserService(userRepository)
	return userService
}
