// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/lucasd-coder/fast-feet/pkg/mongodb"
	"github.com/lucasd-coder/fast-feet/user-manger-service/config"
	"github.com/lucasd-coder/fast-feet/user-manger-service/internal/domain/user/repository"
	"github.com/lucasd-coder/fast-feet/user-manger-service/internal/domain/user/service"
	"github.com/lucasd-coder/fast-feet/user-manger-service/internal/provider/validator"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func InitializeUserRepository() *repository.UserRepository {
	configConfig := config.GetConfig()
	client := mongodb.GetClientMongoDB()
	userRepository := repository.NewUserRepository(configConfig, client)
	return userRepository
}

func InitializeValidator() *validator.Validation {
	validation := validator.NewValidation()
	return validation
}

func InitializeUserService() *service.UserService {
	userRepository := InitializeUserRepository()
	validation := InitializeValidator()
	userService := service.NewUserService(userRepository, validation)
	return userService
}
