version: '3.4'

services:
  accessauthservice:
    image: accessauthservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/go/src
