// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/lucasd-coder/router-service/internal/controller"
	"github.com/lucasd-coder/router-service/internal/domain/user/service"
	"github.com/lucasd-coder/router-service/internal/provider/validator"
)

// Injectors from wire.go:

func InitializeValidator() *validator.Validation {
	validation := validator.NewValidation()
	return validation
}

func InitializeUserService() *service.UserService {
	validation := InitializeValidator()
	userService := service.NewUserService(validation)
	return userService
}

func InitializeUserController() *controller.UserController {
	userService := InitializeUserService()
	userController := controller.NewUserController(userService)
	return userController
}
