version: '3.4'

services:
  auth-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    volumes:
      - .:/go/src
    env_file:
      - .env
