app:
  name: business-service
  version: 1.0.0

logger:
  log_level: info

grpc:
  port: 50053

integration:
  grpc:
    user-manager-service:
      url: localhost:50052
      max-retry: 3
  rabbit-mq:
    queue:
      user-events:
        url: rabbit://business-service-user-events
        max-retry: 5
        poll-delay-in-milliseconds: 100
        max-concurrent-messages: 10