app:
  name: user-manger-service
  version: 1.0.0

logger:
  log_level: ${LOG_LEVEL:info}

grpc:
  port: ${GRPC_PORT:50051}

mongodb:
  url: mongodb://admin:admin123@host.docker.internal:27017/user-manger-service?authSource=admin
  connTimeout: 10s
  database: user-manger-service
  collections:
    user:
      collection: "users"