app:
  name: user-manger-service
  version: 1.0.0

logger:
  log_level: info

grpc:
  port: 50052

mongodb:
  url: mongodb://admin:admin123@localhost:27017/fast-feet?connect=direct&authSource=admin
  connTimeout: 10s
  database: user-manger-service
  collections:
    user:
      collection: "users"

