app:
  name: business-service
  version: 1.0.0

logger:
  log-level: info
  report-caller: false

grpc:
  port: 50053

integration:
  grpc:
    user-manager-service:
      url: localhost:50052
      max-retry: 3
  http:
    access-auth-service:
      url: http://localhost:8081
      max-conn: 20
      max-routes: 20
      read-timeout: 10s
      conn-timeout: 10s
      debug: true
      request-timeout: 60s
      max-retry: 3
      retry-wait-time: 5s
      retry-max-wait-time: 20s
  keycloak:
      token-url: "http://localhost:8080/realms/fastfeet/protocol/openid-connect/token"      
      username: business-service
      password: "&&u1PG9OE*c8"     
      client-id: business-service
      client-secret: lM3euOgR3HIYyCuLmpd0XWza1y6tnnqu
      request-timeout: 60s     
  rabbit-mq:
    queue:
      user-events:
        url: rabbit://business-service-user-events
        max-retry: 5
        poll-delay-in-milliseconds: 100
        max-concurrent-messages: 10