app:
  name: order-data-service
  version: 1.0.0

logger:
  log_level: ${LOG_LEVEL:info}

grpc:
  port: ${GRPC_PORT:50051}

mongodb:
  url: ${MONGODB_URL}
  connTimeout: 10s
  database: fast-feet
  collections:
    order:
      collection: "orders"
      max-time: "2s"