app:
  name: user-manger-service
  version: 1.0.0

logger:
  log_level: ${LOG_LEVEL}

grpc:
  port: ${GRPC_PORT}

mongodb:
  url: mongodb://admin:admin123@localhost:27017/user-manger-service?connect=direct&authSource=admin
  connTimeout: 10s
  database: user-manger-service
  collections:
    user:
      collection: "users"