app:
  name: router-service
  version: 1.0.0
  aes-key: 46cf5df2-d530-4532-92c4-fc3bd562dbee


logger:
  log_level: info

server:
  port: 8085
  readTimeout: 10s
  writeTimeout: 10s

integration:
  grpc:
    business-service:
      url: localhost:50053
      max-retry: 3
  rabbit-mq:
    topic:
      user-events:
        url: rabbit://router-service-user-events
        max-retry: 3
      order-events:
        url: rabbit://router-service-order-events
        max-retry: 3