app:
  name: business-service
  version: 1.0.0
  aes-key: ${AES_KEY}

logger:
  log_level: ${LOG_LEVEL}
  report-caller: false

grpc:
  port: ${GRPC_PORT}

integration:
  grpc:
    user-manager-service:
      url: localhost:50052
      max-retry: 3
  http:
    access-auth-service:
      url: http://localhost:8081
      max-conn: 20
      max-routes: 20
      read-timeout: 10s
      conn-timeout: 10s
      debug: true
      request-timeout: 60s
      max-retry: 3
      retry-wait-time: 5s
      retry-max-wait-time: 20s
  keycloak:
      token-url: ${TOKEN_URL}      
      username: ${USERNAME}
      password: ${PASSWORD}   
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
      request-timeout: 60s
  rabbit-mq:
    queue:
      user-events:
        url: rabbit://business-service-user-events
        max-retry: 5
        poll-delay-in-milliseconds: 100
        max-concurrent-messages: 10