// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/lucasd-coder/fast-feet/order-data-service/config"
	"github.com/lucasd-coder/fast-feet/order-data-service/internal/domain/order/repository"
	"github.com/lucasd-coder/fast-feet/order-data-service/internal/provider/validator"
	"github.com/lucasd-coder/fast-feet/pkg/mongodb"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func InitializeValidator() *validator.Validation {
	validation := validator.NewValidation()
	return validation
}

func InitializeOrderRepository() *repository.OrderRepository {
	configConfig := config.GetConfig()
	client := mongodb.GetClientMongoDB()
	orderRepository := repository.NewOrderRepository(configConfig, client)
	return orderRepository
}
