apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manger-service
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: user-manger-service
  template:
    metadata:
      labels:
        app: user-manger-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/health'
    spec:
      containers:
        - name: user-manger-service
          image: lucasd-coder/user-manger-service:latest          
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: 1         
          env:
            - name: LOG_LEVEL
              value: info
            - name: GRPC_PORT
              value: "50051"
            - name: HTTP_PORT
              value: "8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost"
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: username
                  key: mongo-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: password
                  key: mongo-password
            - name: MONGODB_URL
              value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@server-mongo:27017/fast-feet?connect=direct&authSource=admin"
          ports:
            - containerPort: 50051
          readinessProbe:
            httpGet:
              port: 8080
              path: "/health"
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:            
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 45
            periodSeconds: 10
          lifecycle:
              preStop:
                exec:
                  command:
                    - /bin/sleep
                    - "30"
