apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
  labels:
    app: business-service
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: business-service
  template:
    metadata:
      labels:
        app: business-service
      annotations:
        prometheus.io/scrape: 'true'        
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: business-service
          image: lucasd-coder/business-service:latest      
          resources:
            requests:
              memory: "500Mi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "2"     
          env:
            - name: LOG_LEVEL
              value: info
            - name: GRPC_PORT
              value: "50051"
            - name: HTTP_PORT
              value: "8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "opentelemetry-collector.default.svc.cluster.local:4317"
            - name: USER_MANAGER_URL
              value: "user-manger-service.default.svc.cluster.local:50051"
            - name: ORDER_DATA_URL
              value: "order-data-service.default.svc.cluster.local:50051"
            - name: ACCESS_AUTH_URL
              value: "http://access-auth-service.default.svc.cluster.local:8080"
            - name: KEYCLOAK_URL
              value: "http://keycloak.default.svc.cluster.local:80/auth/realms/fastfeet/protocol/openid-connect/token"
            - name: VIA_CEP_URL
              value: "https://viacep.com.br"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: business-service-keycloak-username
                  key: keycloak-username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: business-service-keycloak-password
                  key: keycloak-password
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: business-service-keycloak-client-id
                  key: keycloak-client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: business-service-keycloak-client-secret
                  key: keycloak-client-secret
            - name: AES_KEY
              valueFrom:
                secretKeyRef:
                  name: business-service-aes-key
                  key: aes-key-config
            - name: REDIS_URL
              value: "redis-cluster.default.svc.cluster.local:6379"         
            - name: REDIS_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: business-service-redis-password
                  key: REDIS_PASSWORD
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: business-service-rabbitmq-username
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: business-service-rabbitmq-password
                  key: rabbitmq-password
            - name: RABBIT_SERVER_URL
              value: "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@rabbitmq.default.svc.cluster.local:5672/fastfeet"          
          ports:
            - containerPort: 50051
              protocol: TCP  
            - containerPort: 8080           
          readinessProbe:
            httpGet:
              port: 8080
              path: "/health"
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:            
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 45
            periodSeconds: 10
          lifecycle:
              preStop:
                exec:
                  command:
                    - /bin/sleep
                    - "30"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: business-service
  name: business-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  ports:
  - port: 50051
    name: grpc
    protocol: TCP    
    targetPort: 50051
  - port: 8080
    name: http-metrics
    protocol: TCP
    targetPort: 8080
  selector:
    app: business-service

