app:
  name: auth-service
  version: 1.0.0

logger:
  log-level: ${LOG_LEVEL}
  report-caller: false

grpc:
  port: ${GRPC_PORT}

http:
  port: ${HTTP_PORT}
  timeout: 20s

integration:
  http:
    keycloak:
      base-url: ${KEYCLOAK_URL}      
      username: ${KEYCLOAK_USERNAME}
      password: ${KEYCLOAK_PASSWORD}
      realm: ${KEYCLOAK_REALM}
      request-timeout: 60s
      debug: true
  
  otlp:
    url: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    protocol: grpc
    timeout: 20s