# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.


scrape_configs:
  - job_name: krakend
    static_configs:
    - targets: ['krakend_ce:9091']
  - job_name: aggregated-trace-metrics
    static_configs:
    - targets: ['otel_collector:8889']
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8181']
