grafana: 
  testFramework:
    enabled: false
  grafana.ini:
    server:
      domain: local.projectcontour.io
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: contour
    }
    path: "/grafana"