{
 "title": "krakend",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "95h percentile request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_path, http_method) (rate(krakend_opencensus_io_http_server_latency_bucket[$__rate_interval])))",
     "legendFormat": "{{http_method}}-{{http_path}}"
    }
   ]
  },
  {
   "title": "Average handling time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(http_method, http_path, http_status) (krakend_opencensus_io_http_server_request_bytes_count{app=\"krakend\"})",
     "legendFormat": "{{http_method}}-{{http_path}}-{{http_status}}"
    }
   ]
  },
  {
   "title": "Http request total rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(krakend_opencensus_io_http_server_request_bytes_count{app=\"krakend\"}[$__interval])) by (http_method,http_path,http_status)",
     "legendFormat": "{{http_method}}-{{http_path}}-{{http_status}}"
    }
   ]
  }
 ]
}