{
 "title": "pubsub",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Hit Counts for Business Service Order Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(app) (quantile_over_time(0.5, business_service_order_events_hits_total{app=\"business-service\"}[$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Hit Counts for Business Service User Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(app) (quantile_over_time(0.5, business_service_user_events_hits_total{app=\"business-service\"}[$__interval]))\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Subscription error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(business_service_user_events_times_count{app=\"business-service\", queueName=\"business_service_user_events_consumed\",status=\"Error\"}[$__interval])) by (queueName)\n",
     "legendFormat": "{{queueName}}"
    },
    {
     "expr": "sum(rate(business_service_order_events_times_count{app=\"business-service\", queueName=\"business_service_order_events_consumed\",status=\"Error\"}[$__interval])) by (queueName)",
     "legendFormat": "{{queueName}}"
    }
   ]
  },
  {
   "title": "Subscription successfully rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(business_service_user_events_times_count{app=\"business-service\", queueName=\"business_service_user_events_consumed\",status=\"Ok\"}[$__interval])) by (queueName)\n",
     "legendFormat": "{{queueName}}"
    },
    {
     "expr": "sum(rate(business_service_order_events_times_count{app=\"business-service\", queueName=\"business_service_order_events_consumed\",status=\"Ok\"}[$__interval])) by (queueName)",
     "legendFormat": "{{queueName}}"
    }
   ]
  },
  {
   "title": "Subscription Latency for Business Service Order Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(business_service_order_events_times_bucket{app=\"business-service\"}[$__interval])) by (queueName,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscription Latency for Business Service User Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(business_service_user_events_times_bucket{app=\"business-service\"}[$__interval])) by (queueName,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency distribution Subcription Order Events Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " histogram_quantile(0.99, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_consumed\"}[$__interval])) by (le)\n)",
     "legendFormat": "99%"
    },
    {
     "expr": " histogram_quantile(0.95, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_consumed\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "95%"
    },
    {
     "expr": " histogram_quantile(0.90, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_consumed\"}[$__interval])) by (le)\n)",
     "legendFormat": "90%"
    },
    {
     "expr": " histogram_quantile(0.75, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_consumed\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "75%"
    },
    {
     "expr": "\n histogram_quantile(0.50, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_consumed\"}[$__interval])) by (le)\n)",
     "legendFormat": "50%"
    },
    {
     "expr": " histogram_quantile(0.25, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_consumed\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_consumed\"}[$__interval])) by (le)\n)",
     "legendFormat": "10%"
    }
   ]
  },
  {
   "title": "Latency distribution Subcription Order Events Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " histogram_quantile(0.99, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_receive\"}[$__interval])) by (le)\n)",
     "legendFormat": "99%"
    },
    {
     "expr": " histogram_quantile(0.95, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_receive\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "95%"
    },
    {
     "expr": " histogram_quantile(0.90, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_receive\"}[$__interval])) by (le)\n)",
     "legendFormat": "90%"
    },
    {
     "expr": " histogram_quantile(0.75, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_receive\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "75%"
    },
    {
     "expr": "\n histogram_quantile(0.50, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_receive\"}[$__interval])) by (le)\n)",
     "legendFormat": "50%"
    },
    {
     "expr": " histogram_quantile(0.25, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_receive\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum(rate(business_service_order_events_times_bucket{app=\"business-service\", queueName=\"business_service_order_events_receive\"}[$__interval])) by (le)\n)",
     "legendFormat": "10%"
    }
   ]
  },
  {
   "title": "Latency distribution Subcription User Events Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " histogram_quantile(0.99, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_consumed\"}[$__interval])) by (le)\n)",
     "legendFormat": "99%"
    },
    {
     "expr": " histogram_quantile(0.95, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_consumed\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "95%"
    },
    {
     "expr": " histogram_quantile(0.90, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_consumed\"}[$__interval])) by (le)\n)",
     "legendFormat": "90%"
    },
    {
     "expr": " histogram_quantile(0.75, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_consumed\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "75%"
    },
    {
     "expr": "\n histogram_quantile(0.50, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_consumed\"}[$__interval])) by (le)\n)",
     "legendFormat": "50%"
    },
    {
     "expr": " histogram_quantile(0.25, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_consumed\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_consumed\"}[$__interval])) by (le)\n)",
     "legendFormat": "10%"
    }
   ]
  },
  {
   "title": "Latency distribution Subcription User Events Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " histogram_quantile(0.99, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_receive\"}[$__interval])) by (le)\n)",
     "legendFormat": "99%"
    },
    {
     "expr": " histogram_quantile(0.95, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_receive\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "95%"
    },
    {
     "expr": " histogram_quantile(0.90, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_receive\"}[$__interval])) by (le)\n)",
     "legendFormat": "90%"
    },
    {
     "expr": " histogram_quantile(0.75, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_receive\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "75%"
    },
    {
     "expr": "\n histogram_quantile(0.50, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_receive\"}[$__interval])) by (le)\n)",
     "legendFormat": "50%"
    },
    {
     "expr": " histogram_quantile(0.25, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_receive\"}[$__interval])) by (le)\n)\n",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum(rate(business_service_user_events_times_bucket{app=\"business-service\", queueName=\"business_service_user_events_receive\"}[$__interval])) by (le)\n)",
     "legendFormat": "10%"
    }
   ]
  },
  {
   "title": "Status distribution for Business Service User Events Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(business_service_user_events_times_count{app=\"business-service\", queueName=\"business_service_user_events_consumed\"}[$__interval])) by (status)\n/ ignoring(status) group_left sum(rate(business_service_user_events_times_count{app=\"business-service\", queueName=\"business_service_user_events_consumed\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status distribution for Business Service User Events Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(business_service_user_events_times_count{app=\"business-service\", queueName=\"business_service_user_events_receive\"}[$__interval])) by (status)\n/ ignoring(status) group_left sum(rate(business_service_user_events_times_count{app=\"business-service\", queueName=\"business_service_user_events_receive\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status distribution for Business Service Order Events Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(business_service_order_events_times_count{app=\"business-service\", queueName=\"business_service_order_events_consumed\"}[$__interval])) by (status)\n/ ignoring(status) group_left sum(rate(business_service_order_events_times_count{app=\"business-service\", queueName=\"business_service_order_events_consumed\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status distribution for Business Service Order Events Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(business_service_order_events_times_count{app=\"business-service\", queueName=\"business_service_order_events_receive\"}[$__interval])) by (status)\n/ ignoring(status) group_left sum(rate(business_service_order_events_times_count{app=\"business-service\", queueName=\"business_service_order_events_receive\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}