{
 "title": "router-service",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Http request total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(chi_http_requests_total{app=\"router-service\"}) by (method,path,status)",
     "legendFormat": "{{method}}-{{path}}-{{status}}"
    }
   ]
  },
  {
   "title": "Http request total rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(chi_http_requests_total{app=\"router-service\"}[$__interval])) by (method,path,status)",
     "legendFormat": "{{method}}-{{path}}-{{status}}"
    }
   ]
  },
  {
   "title": "95h percentile request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, method) (rate(chi_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  }
 ]
}